/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tpaazkaainiyagunungsindur;

import com.tpaazkaainiyagunungsindur.connection.ConnectionDataBaseMySQL;
import java.awt.Font;
import java.awt.HeadlessException;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author indrasudirman
 */
public class PayBillSPP extends javax.swing.JFrame {
    
    String tampilRupiah;
    BigDecimal paymentAmount;
    BigDecimal [] paymentDecimal = new BigDecimal [12]; 
    
    String biayaPembelajaran;
    String namaSiswa;
    ResultSet resultSet;
    BigDecimal totalBayar;// = new BigDecimal();
    NumberFormat numberFormat = NumberFormat.getNumberInstance(new Locale("ID"));
    Font font = new Font ("Ubuntu", Font.BOLD,16);

    /**
     * Creates new form PayBillSPP
     */
    public PayBillSPP() {
//        this.namaSiswa = jLabel3.getText();
        initComponents();
        
        
    }

    public PayBillSPP(String noInduk) {
//        this.namaSiswa = jLabel3.getText();
        initComponents();
        jButton2.setVisible(false);
        jCheckBox2.setEnabled(false);
        jCheckBox3.setEnabled(false);
        jCheckBox4.setEnabled(false);
        jCheckBox5.setEnabled(false);
        jCheckBox6.setEnabled(false);
        jCheckBox7.setEnabled(false);
        jCheckBox8.setEnabled(false);
        jCheckBox9.setEnabled(false);
        jCheckBox10.setEnabled(false);
        jCheckBox11.setEnabled(false);
        jCheckBox12.setEnabled(false);
        
        
        
        jLabel2.setText(noInduk);
        payBill();
        
        
        jLabel9.setFont(font); 
//        selectedMonth();
//        MainMenu mainMenu = new MainMenu();                    
//        mainMenu.showDataStudentsTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelMainMenuAdm = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));

        jLabelMainMenuAdm.setBackground(new java.awt.Color(1, 1, 1));
        jLabelMainMenuAdm.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabelMainMenuAdm.setForeground(new java.awt.Color(1, 1, 1));
        jLabelMainMenuAdm.setText("<html><font color=\"green\"><center>Pembayaran SPP Siswa</font>\n<p> <font color=\"green\"> TPA Azka Ainiya Gunung Sindur</font></p></center></html>");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tpaazkaainiyagunungsindur/image/bayar.png"))); // NOI18N
        jButton1.setText("Bayar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tpaazkaainiyagunungsindur/image/print.png"))); // NOI18N
        jButton2.setText("Cetak");

        jPanel3.setBackground(new java.awt.Color(254, 254, 254));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "Form Pembayaran SPP", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel1.setText("No Induk Siswa");

        jLabel2.setText("No Available");

        jLabel3.setText("No Available");

        jLabel4.setText("Nama Siswa");

        jLabel5.setText("Tagihan SPP");

        jLabel6.setText("No Available");

        jLabel7.setText("Bayar");

        jPanel2.setBackground(new java.awt.Color(254, 254, 254));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jCheckBox8.setText("5 Bulan");
        jCheckBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox8ActionPerformed(evt);
            }
        });

        jCheckBox1.setText("1 Bulan");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox10.setText("10 Bulan");
        jCheckBox10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox10ActionPerformed(evt);
            }
        });

        jCheckBox5.setText("8 Bulan");
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });

        jCheckBox7.setText("6 Bulan");
        jCheckBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox7ActionPerformed(evt);
            }
        });

        jCheckBox11.setText("12 Bulan");
        jCheckBox11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox11ActionPerformed(evt);
            }
        });

        jCheckBox9.setText("9 Bulan");
        jCheckBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox9ActionPerformed(evt);
            }
        });

        jCheckBox3.setText("3 Bulan");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        jCheckBox6.setText("7 Bulan");
        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
            }
        });

        jCheckBox12.setText("11 Bulan");
        jCheckBox12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox12ActionPerformed(evt);
            }
        });

        jCheckBox4.setText("4 bulan");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });

        jCheckBox2.setText("2 Bulan");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jCheckBox1)
                        .addGap(58, 58, 58)
                        .addComponent(jCheckBox2)
                        .addGap(72, 72, 72)
                        .addComponent(jCheckBox3)
                        .addGap(76, 76, 76)
                        .addComponent(jCheckBox4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox8)
                            .addComponent(jCheckBox9))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox7)
                            .addComponent(jCheckBox10))
                        .addGap(64, 64, 64)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox6)
                            .addComponent(jCheckBox12))
                        .addGap(68, 68, 68)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox11)
                            .addComponent(jCheckBox5))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox3)
                    .addComponent(jCheckBox4))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox8)
                    .addComponent(jCheckBox7)
                    .addComponent(jCheckBox6)
                    .addComponent(jCheckBox5))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox9)
                    .addComponent(jCheckBox10)
                    .addComponent(jCheckBox12)
                    .addComponent(jCheckBox11))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel8.setText("Total");

        jLabel9.setText("Rp.0,");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(111, 111, 111)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(jLabelMainMenuAdm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(154, 154, 154)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMainMenuAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox10ActionPerformed
        selectedMonth();
        if (jCheckBox10.isSelected()) {
            paymentDecimal[9] = paymentAmount.multiply(new BigDecimal(10));
            
//            paymentDecimal = paymentDecimal.multiply(new BigDecimal(3));            
            System.out.println("Harganya Rp" + paymentDecimal[9]);
            tampilRupiah = numberFormat.format((paymentDecimal[9]));
            jLabel9.setText("Rp"+tampilRupiah);
        } else {
//            paymentDecimal = paymentDecimal.divide(new BigDecimal(3)); 
            System.out.println("Harganya Rp"+paymentDecimal[8]);
            tampilRupiah = numberFormat.format((paymentDecimal[8]));
            jLabel9.setText("Rp"+tampilRupiah);
        }
//        jCheckBox12.setEnabled(true);
    }//GEN-LAST:event_jCheckBox10ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        yakinBayar();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
//        payBillMonth();
        selectedMonth();
        if (jCheckBox1.isSelected()) {
            paymentDecimal[0] = paymentAmount;
            System.out.println("Harganya Rp" + paymentDecimal[0]);
            tampilRupiah = numberFormat.format((paymentDecimal[0]));
            jLabel9.setText("Rp"+tampilRupiah);
            
        } else {
            System.out.println("Harganya Rp0.");
            jLabel9.setText("Rp0.-");
        }
        
//        if (jCheckBox1.isSelected()) {
//            jLabel9.setText("Rp"+tampilRupiah);
//            jCheckBox2.setEnabled(true);
//            JOptionPane.showMessageDialog(null, paymentDecimal);
//        } else if (jCheckBox2.isSelected()) {
//            BigDecimal oneMonth = paymentDecimal.multiply(paymentDecimal);
//            jLabel9.setText("Rp"+oneMonth);
//            JOptionPane.showMessageDialog(null, oneMonth);
//            jCheckBox3.setEnabled(false);
//            
//        } else {}
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        selectedMonth();
        if (jCheckBox2.isSelected()) {
               paymentDecimal[1] = paymentAmount.multiply(new BigDecimal(2)); 
//            paymentDecimal = paymentDecimal.multiply(new BigDecimal(2));            
            System.out.println("Harganya Rp" + paymentDecimal[1]);
            tampilRupiah = numberFormat.format((paymentDecimal[1]));
            jLabel9.setText("Rp"+tampilRupiah);
        } else {
//            paymentDecimal = paymentDecimal.divide(new BigDecimal(2)); 
            System.out.println("Harganya Rp"+paymentDecimal[0]);
            tampilRupiah = numberFormat.format((paymentDecimal[0]));
            jLabel9.setText("Rp"+tampilRupiah);
        }
//        paymentDecimal = paymentDecimal.multiply(new BigDecimal(2));
//        System.out.println("Harganya Rp" + paymentDecimal);
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        selectedMonth();
        if (jCheckBox3.isSelected()) {
            paymentDecimal[2] = paymentAmount.multiply(new BigDecimal(3));
//            paymentDecimal = paymentDecimal.multiply(new BigDecimal(3));            
            System.out.println("Harganya Rp" + paymentDecimal[2]);
            tampilRupiah = numberFormat.format((paymentDecimal[2]));
            jLabel9.setText("Rp"+tampilRupiah);
        } else {
//            paymentDecimal = paymentDecimal.divide(new BigDecimal(3)); 
            System.out.println("Harganya Rp"+paymentDecimal[1]);
            tampilRupiah = numberFormat.format((paymentDecimal[1]));
            jLabel9.setText("Rp"+tampilRupiah);
        }
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        selectedMonth();
        if (jCheckBox4.isSelected()) {
            paymentDecimal[3] = paymentAmount.multiply(new BigDecimal(4));
//            paymentDecimal = paymentDecimal.multiply(new BigDecimal(3));            
            System.out.println("Harganya Rp" + paymentDecimal[3]);
            tampilRupiah = numberFormat.format((paymentDecimal[3]));
            jLabel9.setText("Rp"+tampilRupiah);
        } else {
//            paymentDecimal = paymentDecimal.divide(new BigDecimal(3)); 
            System.out.println("Harganya Rp"+paymentDecimal[2]);
            tampilRupiah = numberFormat.format((paymentDecimal[2]));
            jLabel9.setText("Rp"+tampilRupiah);
        }
//        jCheckBox8.setEnabled(true);
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jCheckBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox8ActionPerformed
        selectedMonth();
        if (jCheckBox8.isSelected()) {
            paymentDecimal[4] = paymentAmount.multiply(new BigDecimal(5));
//            paymentDecimal = paymentDecimal.multiply(new BigDecimal(3));            
            System.out.println("Harganya Rp" + paymentDecimal[4]);
            tampilRupiah = numberFormat.format((paymentDecimal[4]));
            jLabel9.setText("Rp"+tampilRupiah);
        } else {
//            paymentDecimal = paymentDecimal.divide(new BigDecimal(3)); 
            System.out.println("Harganya Rp"+paymentDecimal[3]);
            tampilRupiah = numberFormat.format((paymentDecimal[3]));
            jLabel9.setText("Rp"+tampilRupiah);
        }
//        jCheckBox7.setEnabled(true);
    }//GEN-LAST:event_jCheckBox8ActionPerformed

    private void jCheckBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox7ActionPerformed
        selectedMonth();
        if (jCheckBox7.isSelected()) {
            paymentDecimal[5] = paymentAmount.multiply(new BigDecimal(6));
//            paymentDecimal = paymentDecimal.multiply(new BigDecimal(3));            
            System.out.println("Harganya Rp" + paymentDecimal[5]);
            tampilRupiah = numberFormat.format((paymentDecimal[5]));
            jLabel9.setText("Rp"+tampilRupiah);
        } else {
//            paymentDecimal = paymentDecimal.divide(new BigDecimal(3)); 
            System.out.println("Harganya Rp"+paymentDecimal[4]);
            tampilRupiah = numberFormat.format((paymentDecimal[4]));
            jLabel9.setText("Rp"+tampilRupiah);
        }
//        jCheckBox6.setEnabled(true);
    }//GEN-LAST:event_jCheckBox7ActionPerformed

    private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed
        selectedMonth();
        if (jCheckBox6.isSelected()) {
            paymentDecimal[6] = paymentAmount.multiply(new BigDecimal(7));
//            paymentDecimal = paymentDecimal.multiply(new BigDecimal(3));            
            System.out.println("Harganya Rp" + paymentDecimal[6]);
            tampilRupiah = numberFormat.format((paymentDecimal[6]));
            jLabel9.setText("Rp"+tampilRupiah);
        } else {
//            paymentDecimal = paymentDecimal.divide(new BigDecimal(3)); 
            System.out.println("Harganya Rp"+paymentDecimal[5]);
            tampilRupiah = numberFormat.format((paymentDecimal[5]));
            jLabel9.setText("Rp"+tampilRupiah);
        }
//        jCheckBox5.setEnabled(true);
    }//GEN-LAST:event_jCheckBox6ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        selectedMonth();
        if (jCheckBox5.isSelected()) {
            paymentDecimal[7] = paymentAmount.multiply(new BigDecimal(8));
//            paymentDecimal = paymentDecimal.multiply(new BigDecimal(3));            
            System.out.println("Harganya Rp" + paymentDecimal[7]);
            tampilRupiah = numberFormat.format((paymentDecimal[7]));
            jLabel9.setText("Rp"+tampilRupiah);
//            paymentDecimal = paymentDecimal.divide(new BigDecimal(3)); 
            
        } else {
            System.out.println("Harganya Rp"+paymentDecimal[6]);
            tampilRupiah = numberFormat.format((paymentDecimal[6]));
            jLabel9.setText("Rp"+tampilRupiah);
        }
//        jCheckBox9.setEnabled(true);
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jCheckBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox9ActionPerformed
        selectedMonth();
        if (jCheckBox9.isSelected()) {
            paymentDecimal[8] = paymentAmount.multiply(new BigDecimal(9));
//            paymentDecimal = paymentDecimal.multiply(new BigDecimal(3));            
            System.out.println("Harganya Rp" + paymentDecimal[8]);
            tampilRupiah = numberFormat.format((paymentDecimal[8]));
            jLabel9.setText("Rp"+tampilRupiah);
            
        } else {
//            paymentDecimal = paymentDecimal.divide(new BigDecimal(3)); 
            System.out.println("Harganya Rp"+paymentDecimal[7]);
            tampilRupiah = numberFormat.format((paymentDecimal[7]));
            jLabel9.setText("Rp"+tampilRupiah);
        }
//        jCheckBox10.setEnabled(true);
    }//GEN-LAST:event_jCheckBox9ActionPerformed

    private void jCheckBox12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox12ActionPerformed
        selectedMonth();
        if (jCheckBox12.isSelected()) {
            paymentDecimal[10] = paymentAmount.multiply(new BigDecimal(11));
//            paymentDecimal = paymentDecimal.multiply(new BigDecimal(3));            
            System.out.println("Harganya Rp" + paymentDecimal[10]);
            tampilRupiah = numberFormat.format((paymentDecimal[10]));
            jLabel9.setText("Rp"+tampilRupiah);
            
        } else {
//            paymentDecimal = paymentDecimal.divide(new BigDecimal(3)); 
            System.out.println("Harganya Rp"+paymentDecimal[9]);
            tampilRupiah = numberFormat.format((paymentDecimal[9]));
            jLabel9.setText("Rp"+tampilRupiah);
        }
//        jCheckBox11.setEnabled(true);
    }//GEN-LAST:event_jCheckBox12ActionPerformed

    private void jCheckBox11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox11ActionPerformed
        selectedMonth();
        if (jCheckBox11.isSelected()) {
            paymentDecimal[11] = paymentAmount.multiply(new BigDecimal(12));
            
//            paymentDecimal = paymentDecimal.multiply(new BigDecimal(3));            
            System.out.println("Harganya Rp" + paymentDecimal[11]);
            tampilRupiah = numberFormat.format((paymentDecimal[11]));
            jLabel9.setText("Rp"+tampilRupiah);
        } else {
//            paymentDecimal = paymentDecimal.divide(new BigDecimal(3)); 
            System.out.println("Harganya Rp"+paymentDecimal[10]);
            tampilRupiah = numberFormat.format((paymentDecimal[10]));
            jLabel9.setText("Rp"+tampilRupiah);
        }
    // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PayBillSPP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PayBillSPP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PayBillSPP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PayBillSPP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PayBillSPP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelMainMenuAdm;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

    public void payBill() {
        
        try {
            
            
            
            
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/TPAAzkaAiniya?zeroDateTimeBehavior=convertToNull","root","");
            Statement statement = connection.createStatement();
            String queryRetrieveDataBase = "SELECT `NAME_STUDENT`, `PAYMENT_BILL` FROM `payment` WHERE STUDENT_ID = '" + jLabel2.getText() + "'";
            resultSet = statement.executeQuery(queryRetrieveDataBase);
            
            
            while (resultSet.next())
            {
                paymentAmount = resultSet.getBigDecimal("PAYMENT_BILL");
                biayaPembelajaran = resultSet.getString("PAYMENT_BILL");
                tampilRupiah = numberFormat.format(new BigDecimal(biayaPembelajaran));
                jLabel3.setText(resultSet.getString(1));                
                jLabel6.setText("Rp"+tampilRupiah);
                
//                paymentDecimal[0] = resultSet.getBigDecimal("PAYMENT_BILL");
//                JOptionPane.showMessageDialog(null, paymentDecimal[0]);
                
                
                 
                //JOptionPane.showMessageDialog(null, "Berhasil menampilkan Data");
                
                
                
            } 
        
        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, "Gagal menampilkan Data! "+ e);
        }
    }

    public void payBillMonth() {
//        payBill();
    
        //System.out.println("Harganya "+ paymentDecimal );
        
        
//        jLabel9.setText("Rp"+tampilRupiah);
//        jCheckBox2.setEnabled(true);
        
        
        
//        totalBayar = payBill().resultSet.getBigDecimal("PAYMENT_BILL");
    }
    
    private void selectedMonth() {
        int hitung = 0;
        if (jCheckBox1.isSelected()) {
            jCheckBox2.setEnabled(true);
//            jLabel9.setText("Rp"+tampilRupiah);
//            totalBayar = paymentDecimal;
//            System.out.println("Harganya 2 "+ paymentDecimal );
        } else {
            jCheckBox2.setEnabled(false);
//            jLabel9.setText("Rp0.");
        } if (jCheckBox1.isSelected() && jCheckBox2.isSelected()) {
            jCheckBox3.setEnabled(true);
//            totalBayar = paymentDecimal.multiply(new BigDecimal(2)); 
            //BigDecimal result = (totalBayar[1]).add(totalBayar[0]);
//            System.out.println("Bayar");
//            System.out.println("Harganya "+ totalBayar ); 
        } else {
            jCheckBox3.setEnabled(false);
        } if (jCheckBox1.isSelected() && jCheckBox2.isSelected() && jCheckBox3.isSelected()) {
            jCheckBox4.setEnabled(true);
//            totalBayar = paymentDecimal;
//            System.out.println("Bayar");
//            System.out.println("Harganya "+ totalBayar ); 
        } else {
            jCheckBox4.setEnabled(false);
        }
        if (jCheckBox1.isSelected() && jCheckBox2.isSelected() && jCheckBox3.isSelected() && jCheckBox4.isSelected()) {
            jCheckBox8.setEnabled(true);
        } else {
            jCheckBox8.setEnabled(false);
        } if (jCheckBox1.isSelected() && jCheckBox2.isSelected() && jCheckBox3.isSelected() && jCheckBox4.isSelected() && jCheckBox8.isSelected()) {
            jCheckBox7.setEnabled(true);        
        } else {
            jCheckBox7.setEnabled(false);
        } if (jCheckBox1.isSelected() && jCheckBox2.isSelected() && jCheckBox3.isSelected() && jCheckBox4.isSelected() && jCheckBox8.isSelected() && jCheckBox7.isSelected()) {
            jCheckBox6.setEnabled(true);
        } else {
            jCheckBox6.setEnabled(false);
        } if (jCheckBox1.isSelected() && jCheckBox2.isSelected() && jCheckBox3.isSelected() && jCheckBox4.isSelected() && jCheckBox8.isSelected() && jCheckBox7.isSelected() && jCheckBox6.isSelected() ) {
            jCheckBox5.setEnabled(true);
        } else {
            jCheckBox5.setEnabled(false);
        } if (jCheckBox1.isSelected() && jCheckBox2.isSelected() && jCheckBox3.isSelected() && jCheckBox4.isSelected() && jCheckBox8.isSelected() && jCheckBox7.isSelected() && jCheckBox6.isSelected() && jCheckBox5.isSelected()) {
            jCheckBox9.setEnabled(true);
        } else {
            jCheckBox9.setEnabled(false);
        } if (jCheckBox1.isSelected() && jCheckBox2.isSelected() && jCheckBox3.isSelected() && jCheckBox4.isSelected() && jCheckBox8.isSelected() && jCheckBox7.isSelected() && jCheckBox6.isSelected() && jCheckBox5.isSelected() && jCheckBox9.isSelected()) {
            jCheckBox10.setEnabled(true);
        } else {
            jCheckBox10.setEnabled(false);
        } if (jCheckBox1.isSelected() && jCheckBox2.isSelected() && jCheckBox3.isSelected() && jCheckBox4.isSelected() && jCheckBox8.isSelected() && jCheckBox7.isSelected() && jCheckBox6.isSelected() && jCheckBox5.isSelected() && jCheckBox9.isSelected() && jCheckBox10.isSelected()) {
            jCheckBox12.setEnabled(true);
        } else {
            jCheckBox12.setEnabled(false);
        } if (jCheckBox1.isSelected() && jCheckBox2.isSelected() && jCheckBox3.isSelected() && jCheckBox4.isSelected() && jCheckBox8.isSelected() && jCheckBox7.isSelected() && jCheckBox6.isSelected() && jCheckBox5.isSelected() && jCheckBox9.isSelected() && jCheckBox10.isSelected() && jCheckBox12.isSelected()) {
            jCheckBox11.setEnabled(true);
        } else {
            jCheckBox11.setEnabled(false);
        }        
    
    }

    private void yakinBayar() {
        JLabel [] jLabelKonfirmasi = {new JLabel("Anda yakin ingin membayar SPP Siswa: \n"), new JLabel(jLabel3.getText())};
        JLabel [] jLabelKonfirmasiNo = {new JLabel("SPP Siswa: \n"), new JLabel(jLabel3.getText()), new JLabel("\nBatal")};
        JLabel [] jLabelKonfirmasiYes = {new JLabel("SPP Siswa: \n"), new JLabel(jLabel3.getText()), new JLabel("\nBerhasil")};
        Font fontNamaSiswa = new Font ("Ubuntu", Font.BOLD,16);
        jLabelKonfirmasi[1].setFont(fontNamaSiswa);
        jLabelKonfirmasiNo[1].setFont(fontNamaSiswa);
        jLabelKonfirmasiNo[2].setFont(fontNamaSiswa);
        jLabelKonfirmasiYes[1].setFont(fontNamaSiswa);
        jLabelKonfirmasiYes[2].setFont(fontNamaSiswa);
        
        int n = JOptionPane.showConfirmDialog(null, jLabelKonfirmasi,"Konfirmasi",JOptionPane.YES_NO_OPTION);
                if (n == JOptionPane.YES_OPTION) {
                    try {
                        
                        paymentDecimal[0] = paymentAmount;
                        paymentDecimal[1] = paymentAmount.multiply(new BigDecimal(2)); 
                        paymentDecimal[2] = paymentAmount.multiply(new BigDecimal(3));
                        paymentDecimal[3] = paymentAmount.multiply(new BigDecimal(4));
                        paymentDecimal[4] = paymentAmount.multiply(new BigDecimal(5));
                        paymentDecimal[5] = paymentAmount.multiply(new BigDecimal(6));
                        paymentDecimal[6] = paymentAmount.multiply(new BigDecimal(7));
                        paymentDecimal[7] = paymentAmount.multiply(new BigDecimal(8));
                        paymentDecimal[8] = paymentAmount.multiply(new BigDecimal(9));
                        paymentDecimal[9] = paymentAmount.multiply(new BigDecimal(10));
                        paymentDecimal[10] = paymentAmount.multiply(new BigDecimal(11));
                        paymentDecimal[11] = paymentAmount.multiply(new BigDecimal(12));
                        
                        
                        
                        ConnectionDataBaseMySQL connectionDataBaseMySql = new ConnectionDataBaseMySQL();
                        connectionDataBaseMySql.connectionDataBase();
                        Statement statement = connectionDataBaseMySql.connection.createStatement();

                        String queryUpdatingDatabase = "UPDATE payment set PAYMENT_AMOUNT =?, PAYMENT_STATUS =? WHERE NAME_STUDENT =?";//"UPDATE `payment` SET PAYMENT_AMOUNT= ? , PAYMENT_STATUS = ? WHERE NAME_STUDENT = ?"; //UPDATE `payment` SET `PAYMENT_AMOUNT`=100000,`PAYMENT_STATUS`='paid' WHERE NAME_STUDENT = 'Jabriko Banjarnegara Jawa Tengah'

                        PreparedStatement prepareStatement = connectionDataBaseMySql.connection.prepareStatement(queryUpdatingDatabase);
                    
                        if (jCheckBox1.isSelected()) {

//                            String paid;
//                            paymentDecimal[0] = paymentAmount;
//                            System.out.println("Harganya Rp" + paymentDecimal[0]);
    //                        tampilRupiah = numberFormat.format((paymentDecimal[0]));
        //                    jLabel9.setText("Rp"+tampilRupiah);


                            prepareStatement.setBigDecimal(1, paymentDecimal[0]);
                            prepareStatement.setString(2,"PAID" );
                            prepareStatement.setString(3,jLabel3.getText() );
                            prepareStatement.executeUpdate();
//                            JOptionPane.showMessageDialog(null,jLabelKonfirmasiYes);
//                            jButton2.setVisible(true);
                            dispose();

                        } if (jCheckBox1.isSelected() && jCheckBox2.isSelected()) {

//                            String paid;
//                            paymentDecimal[0] = paymentAmount;
//                            System.out.println("Harganya Rp" + paymentDecimal[0]);
    //                        tampilRupiah = numberFormat.format((paymentDecimal[0]));
        //                    jLabel9.setText("Rp"+tampilRupiah);


                            prepareStatement.setBigDecimal(1, paymentDecimal[1]);
                            prepareStatement.setString(2,"PAID" );
                            prepareStatement.setString(3,jLabel3.getText() );
                            prepareStatement.executeUpdate();
//                            JOptionPane.showMessageDialog(null,jLabelKonfirmasiYes);
//                            jButton2.setVisible(true);
                            dispose();

                        } if (jCheckBox1.isSelected() && jCheckBox2.isSelected() && jCheckBox3.isSelected()) {

//                            String paid;
//                            paymentDecimal[0] = paymentAmount;
//                            System.out.println("Harganya Rp" + paymentDecimal[0]);
    //                        tampilRupiah = numberFormat.format((paymentDecimal[0]));
        //                    jLabel9.setText("Rp"+tampilRupiah);


                            prepareStatement.setBigDecimal(1, paymentDecimal[2]);
                            prepareStatement.setString(2,"PAID" );
                            prepareStatement.setString(3,jLabel3.getText() );
                            prepareStatement.executeUpdate();
//                            JOptionPane.showMessageDialog(null,jLabelKonfirmasiYes);
//                            jButton2.setVisible(true);
                            dispose();

                        } if (jCheckBox1.isSelected() && jCheckBox2.isSelected() && jCheckBox3.isSelected() && jCheckBox4.isSelected()) {

                            prepareStatement.setBigDecimal(1, paymentDecimal[3]);
                            prepareStatement.setString(2,"PAID" );
                            prepareStatement.setString(3,jLabel3.getText() );
                            prepareStatement.executeUpdate();
//                            JOptionPane.showMessageDialog(null,jLabelKonfirmasiYes);
//                            jButton2.setVisible(true);
                            dispose();

                        } if (jCheckBox1.isSelected() && jCheckBox2.isSelected() && jCheckBox3.isSelected() && jCheckBox4.isSelected() && jCheckBox8.isSelected()) {

                            prepareStatement.setBigDecimal(1, paymentDecimal[4]);
                            prepareStatement.setString(2,"PAID" );
                            prepareStatement.setString(3,jLabel3.getText() );
                            prepareStatement.executeUpdate();
//                            JOptionPane.showMessageDialog(null,jLabelKonfirmasiYes);
//                            jButton2.setVisible(true);
                            dispose();

                        } if (jCheckBox1.isSelected() && jCheckBox2.isSelected() && jCheckBox3.isSelected() && jCheckBox4.isSelected() && jCheckBox8.isSelected() && jCheckBox7.isSelected()) {

                            prepareStatement.setBigDecimal(1, paymentDecimal[5]);
                            prepareStatement.setString(2,"PAID" );
                            prepareStatement.setString(3,jLabel3.getText() );
                            prepareStatement.executeUpdate();
//                            JOptionPane.showMessageDialog(null,jLabelKonfirmasiYes);
//                            jButton2.setVisible(true);
                            dispose();

                        } if (jCheckBox1.isSelected() && jCheckBox2.isSelected() && jCheckBox3.isSelected() && jCheckBox4.isSelected() && jCheckBox8.isSelected() && jCheckBox7.isSelected() && jCheckBox6.isSelected()) {

                            prepareStatement.setBigDecimal(1, paymentDecimal[6]);
                            prepareStatement.setString(2,"PAID" );
                            prepareStatement.setString(3,jLabel3.getText() );
                            prepareStatement.executeUpdate();
//                            JOptionPane.showMessageDialog(null,jLabelKonfirmasiYes);
//                            jButton2.setVisible(true);
                            dispose();

                        } if (jCheckBox1.isSelected() && jCheckBox2.isSelected() && jCheckBox3.isSelected() && jCheckBox4.isSelected() && jCheckBox8.isSelected() && jCheckBox7.isSelected() && jCheckBox6.isSelected() && jCheckBox5.isSelected()) {

                            prepareStatement.setBigDecimal(1, paymentDecimal[7]);
                            prepareStatement.setString(2,"PAID" );
                            prepareStatement.setString(3,jLabel3.getText() );
                            prepareStatement.executeUpdate();
//                            JOptionPane.showMessageDialog(null,jLabelKonfirmasiYes);
//                            jButton2.setVisible(true);
                            dispose();

                        } if (jCheckBox1.isSelected() && jCheckBox2.isSelected() && jCheckBox3.isSelected() && jCheckBox4.isSelected() && jCheckBox8.isSelected() && jCheckBox7.isSelected() && jCheckBox6.isSelected() && jCheckBox5.isSelected() && jCheckBox9.isSelected()) {

                            prepareStatement.setBigDecimal(1, paymentDecimal[8]);
                            prepareStatement.setString(2,"PAID" );
                            prepareStatement.setString(3,jLabel3.getText() );
                            prepareStatement.executeUpdate();
//                            JOptionPane.showMessageDialog(null,jLabelKonfirmasiYes);
//                            jButton2.setVisible(true);
                            dispose();

                        } if (jCheckBox1.isSelected() && jCheckBox2.isSelected() && jCheckBox3.isSelected() && jCheckBox4.isSelected() && jCheckBox8.isSelected() && jCheckBox7.isSelected() && jCheckBox6.isSelected() && jCheckBox5.isSelected() && jCheckBox9.isSelected() && jCheckBox10.isSelected()) {

                            prepareStatement.setBigDecimal(1, paymentDecimal[9]);
                            prepareStatement.setString(2,"PAID" );
                            prepareStatement.setString(3,jLabel3.getText() );
                            prepareStatement.executeUpdate();
//                            JOptionPane.showMessageDialog(null,jLabelKonfirmasiYes);
//                            jButton2.setVisible(true);
                            dispose();

                        } if (jCheckBox1.isSelected() && jCheckBox2.isSelected() && jCheckBox3.isSelected() && jCheckBox4.isSelected() && jCheckBox8.isSelected() && jCheckBox7.isSelected() && jCheckBox6.isSelected() && jCheckBox5.isSelected() && jCheckBox9.isSelected() && jCheckBox10.isSelected() && jCheckBox12.isSelected()) {

                            prepareStatement.setBigDecimal(1, paymentDecimal[10]);
                            prepareStatement.setString(2,"PAID" );
                            prepareStatement.setString(3,jLabel3.getText() );
                            prepareStatement.executeUpdate();
//                            JOptionPane.showMessageDialog(null,jLabelKonfirmasiYes);
//                            jButton2.setVisible(true);
                            dispose();

                        } if (jCheckBox1.isSelected() && jCheckBox2.isSelected() && jCheckBox3.isSelected() && jCheckBox4.isSelected() && jCheckBox8.isSelected() && jCheckBox7.isSelected() && jCheckBox6.isSelected() && jCheckBox5.isSelected() && jCheckBox9.isSelected() && jCheckBox10.isSelected() && jCheckBox12.isSelected() && jCheckBox11.isSelected()) {

                            prepareStatement.setBigDecimal(1, paymentDecimal[11]);
                            prepareStatement.setString(2,"PAID" );
                            prepareStatement.setString(3,jLabel3.getText() );
                            prepareStatement.executeUpdate();
                            
//                            jButton2.setVisible(true);
                            dispose();

                        }
                        JOptionPane.showMessageDialog(null,jLabelKonfirmasiYes);
//                      
//                        MainMenu mainMenu = new MainMenu();                    
//                        mainMenu.showDataStudentsTable();
//                        
//                        DefaultTableModel defaultTableModel = (DefaultTableModel).getModel
//                        defaultTableModel.setRowCount(0); 
                        
                        
                        
                    
                    } catch (SQLException | HeadlessException e) {
                        JOptionPane.showMessageDialog(null," Error pembayaran SPP"+ e);
                    
                    }
                    
                    
                    
                } else if (n ==JOptionPane.NO_OPTION) {
                    JOptionPane.showMessageDialog(null, jLabelKonfirmasiNo);

                }
    }
    
    
}
